//ACTIONS TYPES FOR GATEWAY
export const REGISTER_GATEWAY_START = "REGISTER_GATEWAY_START"
export const REGISTER_GATEWAY_END = "REGISTER_GATEWAY_END"
export const REGISTER_GATEWAY_FAIL = "REGISTER_GATEWAY_FAIL"

export const GET_ALL_GATEWAY_START = "GET_ALL_GATEWAY_START"
export const GET_ALL_GATEWAY_END = "GET_ALL_GATEWAY_END"
export const GET_ALL_GATEWAY_FAIL = "GET_ALL_GATEWAY_FAIL"

//ACTIONS TYPES FOR DEVICE
export const REGISTER_DEVICE_START = "REGISTER_DEVICE_START"
export const REGISTER_DEVICE_END = "REGISTER_DEVICE_END"
export const REGISTER_DEVICE_FAIL = "REGISTER_DEVICE_FAIL"

export const GET_ALL_DEVICE_START = "GET_ALL_DEVICE_START"
export const GET_ALL_DEVICE_END = "GET_ALL_DEVICE_END"
export const GET_ALL_DEVICE_FAIL = "GET_ALL_DEVICE_FAIL"

export const DELETE_DEVICE_START = "DELETE_DEVICE_START"
export const DELETE_DEVICE_END = "DELETE_DEVICE_END"
export const DELETE_DEVICE_FAIL = "DELETE_DEVICE_FAIL"

export const UPDATE_DEVICE_START = "UPDATE_DEVICE_START"
export const UPDATE_DEVICE_END = "UPDATE_DEVICE_END"
export const UPDATE_DEVICE_FAIL = "UPDATE_DEVICE_FAIL"